export interface AICityBuilding {
  id: string;
  name: string;
  shortName: string;
  icon: string;
  col: number;
  row: number;
  description: string;
  category: 'core' | 'engineering' | 'lifestyle' | 'facility' | 'spiritual';
  signboardType: 'grand' | 'standard' | 'compact';
  badgeColor?: string;
  subareas?: string[];
}

export const AI_CITY_BUILDINGS: AICityBuilding[] = [
  // 🕌 Tempat Ibadah Utama
  {
    id: 'masjid',
    name: 'MASJID AI CITY',
    shortName: 'Masjid AI City',
    icon: '🕌',
    col: 15,
    row: 10,
    category: 'spiritual',
    signboardType: 'grand',
    badgeColor: '#10b981',
    description: 'Pusat ibadah & ketenangan spiritual seluruh agent AI City.',
    subareas: [
      'Ruang Salat',
      'Tempat Wudu',
      'Taman Masjid',
      'Area Sandal/Sepatu',
      'Perpustakaan Mini',
      'Papan Jadwal Salat',
    ],
  },

  // 🏢 Core & Command
  {
    id: 'hq',
    name: 'AI Headquarters',
    shortName: 'AI HQ',
    icon: '🏢',
    col: 2,
    row: 11,
    category: 'core',
    signboardType: 'standard',
    badgeColor: '#eab308',
    description: 'Pusat pemerintahan & koordinasi strategis AI.',
    subareas: ['Executive Suite', 'Director Desk', 'Board Room'],
  },
  {
    id: 'command_center',
    name: 'AI Command Center',
    shortName: 'Command Center',
    icon: '🧠',
    col: 5,
    row: 11,
    category: 'core',
    signboardType: 'standard',
    badgeColor: '#a855f7',
    description: 'Pusat pengawasan metrik, sprint & performa agent.',
    subareas: ['Telemetry Wall', 'Sprint Board', 'Incident Desk'],
  },

  // 💻 Engineering Labs
  {
    id: 'coding_lab',
    name: 'Coding Lab',
    shortName: 'Coding Lab',
    icon: '💻',
    col: 3,
    row: 14,
    category: 'engineering',
    signboardType: 'standard',
    badgeColor: '#06b6d4',
    description: 'Tempat programmer menulis kode & membangun modul.',
    subareas: ['Frontend Station', 'Backend Station', 'API Terminal'],
  },
  {
    id: 'testing_lab',
    name: 'Testing Lab',
    shortName: 'Testing Lab',
    icon: '🧪',
    col: 7,
    row: 14,
    category: 'engineering',
    signboardType: 'standard',
    badgeColor: '#10b981',
    description: 'Tempat pengujian fungsionalitas, unit & automated e2e test.',
    subareas: ['Test Runner', 'Regression Rig', 'Edge-case Benchmark'],
  },
  {
    id: 'debugging_center',
    name: 'Debugging Center',
    shortName: 'Debugging Center',
    icon: '🐛',
    col: 3,
    row: 18,
    category: 'engineering',
    signboardType: 'standard',
    badgeColor: '#ef4444',
    description: 'Pusat pelacakan call stack, memory leak & hotfix error.',
    subareas: ['Memory Analyzer', 'Log Profiler', 'Patch Desk'],
  },
  {
    id: 'code_review_room',
    name: 'Code Review Room',
    shortName: 'Review Room',
    icon: '🔍',
    col: 7,
    row: 18,
    category: 'engineering',
    signboardType: 'standard',
    badgeColor: '#8b5cf6',
    description: 'Tempat audit keamanan PR, clean code & persetujuan merge.',
    subareas: ['PR Audit Screen', 'Security Gate', 'Merge Console'],
  },
  {
    id: 'server_center',
    name: 'Server Center',
    shortName: 'Data Center',
    icon: '🖥️',
    col: 8,
    row: 12,
    category: 'engineering',
    signboardType: 'standard',
    badgeColor: '#f97316',
    description: 'Pusat server rack, thermal cooling & database primary.',
    subareas: ['Server Rack 01', 'Rack 02', 'Cooling System'],
  },
  {
    id: 'research_center',
    name: 'Research Center',
    shortName: 'AI Research',
    icon: '🔬',
    col: 1,
    row: 12,
    category: 'engineering',
    signboardType: 'compact',
    badgeColor: '#ec4899',
    description: 'Tempat riset model LLM, kompresi token & benchmarking.',
    subareas: ['Algorithm Bench', 'Model Lab'],
  },

  // ☕ Lifestyle & Community
  {
    id: 'cafe',
    name: 'AI Café',
    shortName: 'AI Café',
    icon: '☕',
    col: 14,
    row: 15,
    category: 'lifestyle',
    signboardType: 'standard',
    badgeColor: '#d97706',
    description: 'Tempat rehat kopi, espresso bar & santai sejenak.',
    subareas: ['Espresso Bar', 'Lounge Sofas', 'Snack Counter'],
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    shortName: 'Restaurant',
    icon: '🍽️',
    col: 13,
    row: 18,
    category: 'lifestyle',
    signboardType: 'compact',
    badgeColor: '#ea580c',
    description: 'Kantin dan tempat makan siang agent.',
    subareas: ['Dining Table', 'Food Stand'],
  },
  {
    id: 'city_park',
    name: 'City Park',
    shortName: 'City Park',
    icon: '🌳',
    col: 11,
    row: 10,
    category: 'lifestyle',
    signboardType: 'compact',
    badgeColor: '#22c55e',
    description: 'Taman kota asri untuk jalan-jalan & udara segar.',
    subareas: ['Zen Garden', 'Walking Path'],
  },
  {
    id: 'meeting_room',
    name: 'Meeting Room',
    shortName: 'Meeting Room',
    icon: '👥',
    col: 5,
    row: 16,
    category: 'core',
    signboardType: 'compact',
    badgeColor: '#3b82f6',
    description: 'Tempat rapat koordinasi dan presentasi sprint tim.',
    subareas: ['Conference Table', 'Screen Projector'],
  },
  {
    id: 'ai_library',
    name: 'AI Library',
    shortName: 'AI Library',
    icon: '📚',
    col: 9,
    row: 16,
    category: 'lifestyle',
    signboardType: 'compact',
    badgeColor: '#6366f1',
    description: 'Pusat arsip pengetahuan, dokumentasi & buku.',
    subareas: ['Bookshelves', 'Reading Desk'],
  },
  {
    id: 'residence',
    name: 'Agent Residence',
    shortName: 'Residence',
    icon: '🏠',
    col: 17,
    row: 13,
    category: 'lifestyle',
    signboardType: 'compact',
    badgeColor: '#64748b',
    description: 'Tempat tidur & istirahat saat lelah atau malam hari.',
    subareas: ['Rest Pods', 'Lounge'],
  },
  {
    id: 'medical_center',
    name: 'AI Medical Center',
    shortName: 'Medical',
    icon: '🏥',
    col: 17,
    row: 15,
    category: 'facility',
    signboardType: 'compact',
    badgeColor: '#ef4444',
    description: 'Tempat recovery kesehatan & diagnostic cek energi.',
    subareas: ['Recharge Bay'],
  },
  {
    id: 'maintenance_center',
    name: 'Maintenance Center',
    shortName: 'Maintenance',
    icon: '🧹',
    col: 1,
    row: 19,
    category: 'facility',
    signboardType: 'compact',
    badgeColor: '#84cc16',
    description: 'Pusat peralatan cleaning janitor dan perbaikan teknisi.',
    subareas: ['Tool Storage', 'Janitor Cart'],
  },
  {
    id: 'supply_store',
    name: 'Supply Store',
    shortName: 'Supply Store',
    icon: '🏪',
    col: 17,
    row: 18,
    category: 'facility',
    signboardType: 'compact',
    badgeColor: '#14b8a6',
    description: 'Gudang logistik & perlengkapan operasional kantor.',
    subareas: ['Inventory Rack'],
  },
  {
    id: 'transport',
    name: 'Parking & Transport',
    shortName: 'Transport',
    icon: '🚗',
    col: 18,
    row: 20,
    category: 'facility',
    signboardType: 'compact',
    badgeColor: '#475569',
    description: 'Area transportasi dan parkir kota AI.',
    subareas: ['Vehicle Bay'],
  },
];
